# Generated by Django 5.1.2 on 2024-11-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('level', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('course', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
    ]
