# Generated by Django 5.1.2 on 2024-11-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='attendTotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classroom',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
