# Generated by Django 5.1.2 on 2024-11-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_classroom_attendtotal_classroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='courseCode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
