# Generated by Django 5.1.2 on 2024-11-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_classroom_code_classroom_coursecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='roomID',
            field=models.IntegerField(default=0),
        ),
    ]
