# Generated by Django 5.1.2 on 2024-11-04 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_classroom_roomid'),
        ('groups', '0003_remove_instructor_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('dueTime', models.DateTimeField()),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('ended', 'ended'), ('graded', 'graded')], default='ongoing', max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_class', to='classroom.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('graded', 'graded')], default='pending', max_length=20)),
                ('score', models.IntegerField()),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='classroom.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.student')),
            ],
        ),
    ]
