# Generated by Django 5.1.2 on 2024-11-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_submissions_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
