# Generated by Django 5.1.2 on 2024-11-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_alter_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
