# Generated by Django 5.1.2 on 2024-11-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('abbreviation', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('bio', models.TextField()),
                ('educationLevel', models.CharField(choices=[("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.'), ('other', 'other')], default="Bachelor's Degree", max_length=100)),
                ('course', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('level', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('courses', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
    ]
