# Generated by Django 5.1.2 on 2024-11-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='title',
        ),
    ]
