# Generated by Django 5.1.2 on 2024-11-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='role',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Student', 'Student')], default='user', max_length=10),
        ),
    ]
